//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppdeSaude.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alimentos
    {
        public int id { get; set; }
        public string Nome { get; set; }
        public double Calorias { get; set; }
        public string Imagem { get; set; }
        public double Quantidade { get; set; }
        public int utilizador_id { get; set; }
    
        public virtual utilizador utilizador { get; set; }
    }
}
