//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppdeSaude.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consulta
    {
        public int id { get; set; }
        public System.DateTime Data { get; set; }
        public System.TimeSpan Hora { get; set; }
        public int medico_id { get; set; }
        public int medico_nrutente { get; set; }
        public int utilizador_id { get; set; }
        public string Relatorio { get; set; }
    
        public virtual medico medico { get; set; }
        public virtual utilizador utilizador { get; set; }
    }
}
