//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppdeSaude.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicacao
    {
        public int id { get; set; }
        public System.DateTime Datadeinicio { get; set; }
        public string Nome { get; set; }
        public Nullable<System.TimeSpan> Tempo { get; set; }
        public Nullable<System.DateTime> Duracao { get; set; }
        public string Motivo { get; set; }
        public int utilizador_id { get; set; }
    
        public virtual utilizador utilizador { get; set; }
    }
}
