//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppdeSaude.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public medico()
        {
            this.consulta = new HashSet<consulta>();
            this.clinica = new HashSet<clinica>();
        }
    
        public int id { get; set; }
        public string Nome { get; set; }
        public int Nrutente { get; set; }
        public int Contacto { get; set; }
        public int Nrdemedico { get; set; }
        public System.DateTime Datadenascimento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consulta> consulta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clinica> clinica { get; set; }
    }
}
