//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppdeSaude.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registos
    {
        public int id { get; set; }
        public double Peso { get; set; }
        public double Altura { get; set; }
        public System.DateTime Data { get; set; }
        public int utilizador_id { get; set; }
        public int parametrosimc_id { get; set; }
    
        public virtual parametrosimc parametrosimc { get; set; }
        public virtual utilizador utilizador { get; set; }
    }
}
